In [28]:
import pandas as pd

## Read in speech

Read speech from file

In [51]:
import os

path = '/Users/kevcon/ds/metis/metisgh/Project-4/speeches'
speech_files = []

for filename in os.listdir(path):
    speech_files.append(filename)

In [52]:
speech_files

['convention.csv', 'inauguration.csv', 'farewell.csv', 'state_union.csv']

In [65]:
columns = ['type', 'speaker', 'date', 'speech']
df_speeches = pd.DataFrame(columns=columns)

for file in speech_files:
    df_temp = pd.read_csv(path + '/' + file)
    df_speeches = pd.concat([df_speeches, df_temp], ignore_index=True)

55
59
13
229


In [67]:
df_speeches.head()

type          speaker               date  \
0  convention  Hillary Clinton      July 28, 2016   
1  convention      Robert Dole    August 15, 1996   
2  convention   George W. Bush     August 3, 2000   
3  convention   George W. Bush  September 2, 2004   
4  convention      John McCain  September 4, 2008   

                                              speech  
0  Thank you all for the great convention that we...  
1  The folks in Hollywood would be happy to know ...  
2  Thank you. Thank you for this honor. [,],Thank...  
3  When I said those words 4 years ago, none of u...  
4  Tonight, I have a privilege given few American...

In [70]:
df_speeches.loc[df_speeches['speech'].isnull()]

type            speaker  date speech
104  inauguration    Abraham Lincoln  1865    NaN
105  inauguration    Abraham Lincoln  1861    NaN
127   state_union  George Washington  1790    NaN

In [80]:
df_speeches['speaker'].isnull().sum()

0

In [74]:
df_speeches['speaker'].unique()

array(['Hillary Clinton', 'Robert Dole', 'George W. Bush', 'John McCain',
       'Mitt Romney', 'Donald J. Trump', 'Woodrow Wilson', 'Al Smith',
       'Franklin D. Roosevelt', 'Harry S. Truman', 'Adlai Stevenson',
       'Abraham Lincoln', 'James A. Garfield', 'Benjamin Harrison',
       'William McKinley', 'William Howard Taft', 'Charles E. Hughes',
       'Warren G. Harding', 'Calvin Coolidge', 'Herbert Hoover',
       'Wendell Willkie', 'Thomas Dewey', 'Dwight D. Eisenhower',
       'Richard Nixon', 'Barry Goldwater', 'Gerald R. Ford',
       'Ronald Reagan', 'George Bush', 'John F. Kennedy',
       'Lyndon B. Johnson', 'Hubert H. Humphrey', 'George McGovern',
       'Jimmy Carter', 'Walter F. Mondale', 'Michael S. Dukakis',
       'William J. Clinton', 'Albert Gore, Jr.', 'John F. Kerry',
       'Barack Obama', 'John Quincy Adams', 'James Monroe',
       'James Madison', 'Thomas Jefferson', 'by ', 'George Washington',
       'Franklin Delano Roosevelt', ' & ', 'Bill Clinton',
    

In [79]:
df_speeches.loc[(df_speeches['speaker'] == 'by ') | (df_speeches['speaker'] == ' & ')]

type speaker  date  \
62   inauguration     by   1797   
71   inauguration      &   2017   
345   state_union     by   1800   
346   state_union     by   1799   
347   state_union     by   1798   
348   state_union     by   1797   

                                                speech  
62   \nWhen it was first perceived, in early times,...  
71    ,, ,, ,, ,, ,, fellow Americans, and people o...  
345  Gentlemen of the Senate and Gentlemen of the H...  
346  Gentlemen of the Senate and Gentlemen of the H...  
347  Gentlemen of the Senate and Gentlemen of the H...  
348  I was for some time apprehensive that it would...

In [81]:
df_speeches['date'].isnull().sum()

0

In [82]:
df_speeches['date'].unique()

array(['July 28, 2016', 'August 15, 1996', 'August 3, 2000',
       'September 2, 2004', 'September 4, 2008', 'August 30, 2012',
       'July 21, 2016', 'September 2, 1916', 'August 22, 1928',
       'July 2, 1932', 'June 27, 1936', 'July 19, 1940', 'July 20, 1944',
       'July 15, 1948', 'July 26, 1952', 'August 17, 1956',
       'June 27, 1864', 'July 12, 1880', 'September 11, 1888',
       'September 3, 1892', 'July 12, 1900', 'July 28, 1908',
       'June 10, 1916', 'June 12, 1920', 'August 14, 1924',
       'August 11, 1932', 'June 16, 1932', 'August 17, 1940',
       'June 28, 1944', 'June 24, 1948', 'July 11, 1952',
       'August 23, 1956', 'July 28, 1960', 'July 16, 1964',
       'August 8, 1968', 'August 23, 1972', 'August 19, 1976',
       'July 17, 1980', 'August 23, 1984', 'August 18, 1988',
       'August 20, 1992', 'July 15, 1960', 'August 27, 1964',
       'August 29, 1968', 'July 14, 1972', 'July 15, 1976',
       'August 14, 1980', 'July 19, 1984', 'July 21, 1988',
 

In [83]:
df_speeches['date'] = pd.to_datetime(df_speeches['date'])

In [87]:
df_speeches['date'] = df_speeches['date'].apply(lambda x: x.year)

## NLTK Processing

In [3]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

Process text data for insertion into dataframe:

1. Iterate through each speech and split into individual paragraphs
2. Split each paragraph into individual sentences
3. Store each sentence in a list
4. Label speeches, paragraphs and sentences with IDs

In [4]:
speech_list = []
paragraph_list = []
sent_list = []
text = []
i = 0
j = 0
k = 0

for speech in speeches:

    speech = speech.lower()
    paragraphs = list(filter(None, speech.splitlines()))

    for paragraph in paragraphs:

        sentences = sent_tokenize(paragraph)

        for sentence in sentences:

            speech_list.append(speech_names[k])
            paragraph_list.append(i)
            sent_list.append(j)
            j += 1
            text.append(sentence)

        i += 1
        
    k += 1

Create and fill dataframe

In [5]:
columns = ['speech_id', 'paragraph_id', 'sentence_id', 'text']
speech_df = pd.DataFrame(columns=columns)

In [6]:
speech_df['speech_id'] = speech_list
speech_df['paragraph_id'] = paragraph_list
speech_df['sentence_id'] = sent_list
speech_df['text'] = text

In [7]:
speech_df.head()

speech_id  paragraph_id  sentence_id  \
0  1932_FDR             0            0   
1  1932_FDR             1            1   
2  1932_FDR             1            2   
3  1932_FDR             2            3   
4  1932_FDR             2            4   

                                                text  
0  chairman walsh, my friends of the democratic n...  
1  i appreciate your willingness after these six ...  
2  i regret that i am late, but i have no control...  
3  the appearance before a national convention of...  
4  i have started out on the tasks that lie ahead...

### Filter and normalize
for sentence input, define function to: 
1. filter out uninteresting words
2. generalize remaining words
3. return word list

In [8]:
from nltk.corpus import stopwords

def stop_n_lem(sentence):
    
    # import and define words to ignore for analysis
    stop = stopwords.words('english')
    stop += ['.', ',', '(', ')', "'", '"', ';', ':']
    stop = set(stop)
    
    # define lemmatizer
    lemma = nltk.stem.WordNetLemmatizer()
    
    words = word_tokenize(sentence) # split sentence into individual words
    words = [lemma.lemmatize(w) for w in words if w not in stop] # lemmatize non-stop words
    return(words)

### Sentiment Analysis
for text input, define function to return polarity and subjectivity values (sentiment analysis)

In [9]:
from textblob import TextBlob

def feel_me(text):
    
    return(TextBlob(text).sentiment)

In [12]:
speech_clean_df = speech_df
# speech_clean_df['text'] = speech_clean_df['text'].apply(stop_n_lem)
speech_clean_df['text'].apply(stop_n_lem)

0      [chairman, walsh, friend, democratic, national...
1      [appreciate, willingness, six, arduous, day, r...
2      [regret, late, control, wind, heaven, could, t...
3      [appearance, national, convention, nominee, pr...
4      [started, task, lie, ahead, breaking, absurd, ...
5      [friend, may, symbol, intention, honest, avoid...
6                        [nominated, know, thank, honor]
7                [let, also, symbolic, broke, tradition]
8          [let, task, party, break, foolish, tradition]
9      [break, foolish, tradition, leave, republican,...
10     [let, u, highly, resolve, resume, country, 's,...
11     [indomitable, leader, interrupted, march, long...
12     [many, captain, thank, god, still, u, give, u,...
13     [let, u, feel, everything, still, life, u, bod...
14     [many, thing, want, make, position, clear, ear...
15       [admirable, document, platform, adopted, clear]
16                                [accept, 100, percent]
17     [accept, pledge, leave, 

In [17]:
speech_clean_df.head()

speech_id  paragraph_id  sentence_id  \
0  1932_FDR             0            0   
1  1932_FDR             1            1   
2  1932_FDR             1            2   
3  1932_FDR             2            3   
4  1932_FDR             2            4   

                                                text  
0  chairman walsh, my friends of the democratic n...  
1  i appreciate your willingness after these six ...  
2  i regret that i am late, but i have no control...  
3  the appearance before a national convention of...  
4  i have started out on the tasks that lie ahead...

### Word Counts

In [ ]:
from nltk.util import ngrams

from collections import Counter
from operator import itemgetter

from nltk.corpus import stopwords
stop = stopwords.words('english')
stop += ['.', ',', '(', ')', "'", '"']
stop = set(stop)

counter = Counter()

n = 1
for doc in documents:
    words = TextBlob(doc).words  # tokenize words
    words = [w for w in words if w not in stop]   
    bigrams = ngrams(words, n)
    counter += Counter(bigrams)

for phrase, count in counter.most_common(30):
    print('%20s %i' % (" ".join(phrase), count))

### n-grams

In [96]:
speech_df.head()

speech_id  paragraph_id  sentence_id  \
0  1932_FDR             0            0   
1  1932_FDR             1            1   
2  1932_FDR             1            2   
3  1932_FDR             2            3   
4  1932_FDR             2            4   

                                                text  
0  [chairman, walsh, friend, democratic, national...  
1  [appreciate, willingness, six, arduous, day, r...  
2  [regret, late, control, wind, heaven, could, t...  
3  [appearance, national, convention, nominee, pr...  
4  [started, task, lie, ahead, breaking, absurd, ...

## Set up word matrix

In [15]:
text = speech_df['text']

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

# CountVectorizer is a class; so `vectorizer` below represents an instance of that object.
vectorizer = CountVectorizer(ngram_range=(1,2))

# call `fit` to build the vocabulary
vectorizer.fit(text)

# then, use `get_feature_names` to return the tokens
print(vectorizer.get_feature_names())

# finally, call `transform` to convert text to a bag of words
x = vectorizer.transform(text)

['000', '000 000', '000 people', '000 year', '10', '10 or', '100', '100 percent', '12', '12 cents', '120', '120 000', '1776', '18th', '18th amendment', '1928', '1928 the', '1929', '1929 we', '1932', '40', '40 cents', '48', '48 cents', '50', '50 000', '560', '560 000', 'abandon', 'abandon the', 'abandoned', 'abandoned farms', 'able', 'able to', 'abolish', 'abolish useless', 'about', 'about agriculture', 'about our', 'about setting', 'about the', 'about unemployment', 'abroad', 'abroad in', 'absurd', 'absurd traditions', 'accept', 'accept it', 'accept my', 'accept that', 'accomplished', 'accomplished in', 'achieve', 'achieve by', 'acknowledge', 'acknowledge that', 'acknowledgment', 'acknowledgment of', 'acres', 'acres east', 'acres of', 'action', 'action of', 'action that', 'action we', 'acts', 'acts of', 'actual', 'actual conditions', 'actual wording', 'actually', 'actually expanding', 'add', 'add to', 'addition', 'addition to', 'additional', 'additional factor', 'adequate', 'adequate p

In [85]:
print('Sparse Matrix')
# A compressed version; the "sparse" matrix.
print(type(x))
print(x)

print ('Matrix')
x_back = x.toarray()
print(type(x_back))
print(x_back)

Sparse Matrix
<class 'scipy.sparse.csr.csr_matrix'>
  (0, 19)	1
  (0, 651)	1
  (0, 652)	1
  (0, 780)	1
  (0, 782)	1
  (0, 899)	1
  (0, 900)	1
  (0, 1301)	1
  (0, 1307)	1
  (0, 2193)	1
  (0, 2195)	1
  (0, 2219)	1
  (0, 2220)	1
  (0, 2341)	2
  (0, 2344)	1
  (0, 2451)	1
  (0, 3441)	1
  (0, 3483)	1
  (0, 4089)	1
  (0, 4090)	1
  (1, 96)	1
  (1, 97)	1
  (1, 200)	1
  (1, 234)	1
  (1, 328)	1
  :	:
  (191, 1682)	1
  (191, 1864)	1
  (191, 1869)	1
  (191, 2091)	1
  (191, 2093)	1
  (191, 2288)	1
  (191, 2310)	1
  (191, 2601)	1
  (191, 2603)	1
  (191, 2653)	1
  (191, 2981)	1
  (191, 2982)	1
  (191, 3727)	1
  (191, 3735)	1
  (191, 3802)	4
  (191, 3832)	1
  (191, 3858)	1
  (191, 3883)	2
  (191, 4081)	1
  (191, 4082)	1
  (191, 4247)	2
  (191, 4248)	1
  (191, 4249)	1
  (191, 4359)	1
  (191, 4361)	1
Matrix
<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [86]:
pd.DataFrame(x_back, columns=vectorizer.get_feature_names())

000  000 000  000 people  000 year  10  10 or  100  100 percent  12  \
0      0        0           0         0   0      0    0            0   0   
1      0        0           0         0   0      0    0            0   0   
2      0        0           0         0   0      0    0            0   0   
3      0        0           0         0   0      0    0            0   0   
4      0        0           0         0   0      0    0            0   0   
5      0        0           0         0   0      0    0            0   0   
6      0        0           0         0   0      0    0            0   0   
7      0        0           0         0   0      0    0            0   0   
8      0        0           0         0   0      0    0            0   0   
9      0        0           0         0   0      0    0            0   0   
10     0        0           0         0   0      0    0            0   0   
11     0        0           0         0   0      0    0            0   0   
12     0        0           0         0   0      0    0            0   0   
13     0        0           0         0   0      0    0            0   0   
14     0        0           0         0   0      0    0            0   0   
15     0        0           0         0   0      0    0            0   0   
16     0        0           0         0   0      0    1            1   0   
17     0        0           0         0   0      0    0            0   0   
18     0        0           0         0   0      0    0            0   0   
19     0        0           0         0   0      0    0            0   0   
20     0        0           0         0   0      0    0            0   0   
21     0        0           0         0   0      0    0            0   0   
22     0        0           0         0   0      0    0            0   0   
23     0        0           0         0   0      0    0            0   0   
24     0        0           0         0   0      0    0            0   0   
25     0        0           0         0   0      0    0            0   0   
26     0        0           0         0   0      0    0            0   0   
27     0        0           0         0   0      0    0            0   0   
28     0        0           0         0   0      0    0            0   0   
29     0        0           0         0   0      0    0            0   0   
..   ...      ...         ...       ...  ..    ...  ...          ...  ..   
162    0        0           0         0   0      0    0            0   0   
163    0        0           0         0   0      0    0            0   0   
164    0        0           0         0   0      0    0            0   0   
165    0        0           0         0   0      0    0            0   0   
166    0        0           0         0   0      0    0            0   0   
167    0        0           0         0   0      0    0            0   0   
168    0        0           0         0   0      0    0            0   0   
169    0        0           0         0   0      0    0            0   0   
170    0        0           0         0   0      0    0            0   0   
171    0        0           0         0   0      0    0            0   0   
172    0        0           0         0   0      0    0            0   0   
173    0        0           0         0   0      0    0            0   0   
174    0        0           0         0   0      0    0            0   0   
175    0        0           0         0   0      0    0            0   0   
176    0        0           0         0   0      0    0            0   0   
177    0        0           0         0   0      0    0            0   0   
178    0        0           0         0   0      0    0            0   0   
179    0        0           0         0   0      0    0            0   0   
180    0        0           0         0   0      0    0            0   0   
181    0        0           0         0   0      0    0            0   0   
182    0        0           0         0   0      0   